server:
  port: 8080

spring:

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 50MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/green?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 850818
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true

  output:
    ansi:
      enabled: ALWAYS

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          import_files: classpath:db/data.sql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true