--SET REFERENTIAL_INTEGRITY FALSE;
--
--truncate table user;
--truncate table product;
--truncate table option_td;
--truncate table cart_tb;
--truncate table option_tb;
--
--SET REFERENTIAL_INTEGRITY TRUE;
--
--insert into USER (email, password, roles) values ('aamin@green.com', '{bcrypt}$2a$10$xf08ndND/FpEGhyvmDx0PeDKdhoXMjVfTJCDWZUUpgpvdSMzWomyi', 'ROLE_USER');
--insert into USER (email, password, roles) values ('meighteen1@meetup.com', 'dZ1~z{HL', 'ROLE_USER');
--insert into USER (email, password, roles) values ('fmoyes2@google.de', 'jR2!<=rn@IW(sU', 'ROLE_USER');
--insert into USER (email, password, roles) values ('ddupre3@boston.com', 'kK4,Oc,*KKBRMb{', 'ROLE_USER');
--insert into USER (email, password, roles) values ('lasple4@moonfruit.com', 'nW9$`CZVlCDN*g1', 'ROLE_USER');
--
--
--insert into product (image, product_name, price, description) values ('filepath/UUID/fileName', 'Bread - Raisin', 284024, 'description');
--insert into product (image, product_name, price, description) values ('filepath/UUID/fileName', 'Soup - Cream Of Broccoli', 32644, 'description');
--insert into product (image, product_name, price, description) values ('filepath/UUID/fileName', 'Cleaner - Comet', 237218, 'description');
--insert into product (image, product_name, price, description) values ('filepath/UUID/fileName', 'Ecolab Digiclean Mild Fm', 285943, 'description');
--insert into product (image, product_name, price, description) values ('filepath/UUID/fileName', 'Muskox - French Rack', 140777, 'description');
